name: "HA Electric Usage Download"
description: "A HA wrapper for Ted Pearsons electric-usage-downloader"
version: "1.0.0"
slug: "electric-usage-downloader"
init: false
arch:
  - amd64
options:
  extract_days: 2
  smarthub:
    api_url: null
    username: null
    password: null
    account: null
    service_location: null
  influxdb:
    host: null
    auth_token: null
    database: null
    insecure: null
schema:
  extract_days: int(2,45)
  smarthub:
    api_url: url
    username: str
    password: password
    account: int
    service_location: int
  influxdb:
    host: url
    auth_token: password
    database: str
    insecure: bool
